### ISSUE TITLE
std feature flag doesn't override libm

### ISSUE THREAD

**Issue by DavJCosby** [bitshifter/glam-rs#587]
I ran into an [interesting issue](https://github.com/DavJCosby/sled/pull/86#issuecomment-2472223211) the other day while making my crate compatible with no_std.

Our cargo.toml setup looked roughly like this:

```toml
# --snip--
[features]
std = ["glam/std"]

[dependencies]
glam = { version = "0.29", default-features = false, features = ["libm"] }
```

The goal was to use std features whenever they were available and fall back on libm when they weren't. Benchmarks showed, however, that even on std-enabled compilations libm functionality was being preferred. I believe this is unintended behavior, but I wanted to confirm before submitting a PR.

For my crate, I ended up just doing:
```toml
[features]
std = ["glam/std"]
libm = ["glam/libm"]

[dependencies]
glam = { version = "0.29", default-features = false, features = [] }
```
